name: finalmlenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - xgboost
  - pytorch
  - torchvision
  - torchaudio
  - ray-core
  - sympy
  - fastparquet
  - pydot
  - pip
  - pip:
      - captum==0.7.0
      - tqdm==4.66.2
